spring.application.name=realtime-gateway
server.port=8083

collabmind.chat-core.base-url=http://localhost:8081
collabmind.ai-orchestrator.base-url=http://localhost:8084

app.jwt.secret=collabmind-development-secret-key-change-this-later-123456789

management.endpoints.web.exposure.include=health,info

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.listener.ack-mode=record
spring.kafka.consumer.properties.spring.json.trusted.packages=org.collabmind.realtime.event
collabmind.instance-id=${HOSTNAME:${random.uuid}}
collabmind.redis.realtime-channel=collabmind:realtime
collabmind.redis.session-ttl-seconds=90
collabmind.ai.rate-limit-seconds=3
collabmind.ai.request-ttl-seconds=300
collabmind.kafka.message-created-topic=collabmind.message-created.v1
collabmind.kafka.ai-requested-topic=collabmind.ai-requested.v1
collabmind.kafka.ai-dlt-topic=collabmind.ai-requested.v1.DLT
